ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP5.4-5.6\upload_v2.3.x-3.x\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\en-gb\extension .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\ru-ru\extension .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\uk-ua\extension .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\language\ukrainian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.0\upload_v2.3.x-3.x\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.0\upload_v2.1.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\en-gb\extension .\PHP7.0\upload_v2.1.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\ru-ru\extension .\PHP7.0\upload_v2.1.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\uk-ua\extension .\PHP7.0\upload_v2.1.x-2.2\admin\language\ukrainian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.1\upload_v2.3.x-3.x\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.1\upload_v2.1.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\en-gb\extension .\PHP7.1\upload_v2.1.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\ru-ru\extension .\PHP7.1\upload_v2.1.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\uk-ua\extension .\PHP7.1\upload_v2.1.x-2.2\admin\language\ukrainian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.2\upload_v2.3.x-3.x\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\PHP7.2\upload_v2.1.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\en-gb\extension .\PHP7.2\upload_v2.1.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\ru-ru\extension .\PHP7.2\upload_v2.1.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\uk-ua\extension .\PHP7.2\upload_v2.1.x-2.2\admin\language\ukrainian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP5.4-5.6\upload_v2.3.x-3.x\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.0\upload_v2.1.x-2.2\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.0\upload_v2.3.x-3.x\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.1\upload_v2.1.x-2.2\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.1\upload_v2.3.x-3.x\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.2\upload_v2.1.x-2.2\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model\catalog .\PHP7.2\upload_v2.3.x-3.x\admin\model\catalog\ attributico.php /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP5.4-5.6\upload_v2.3.x-3.x\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.0\upload_v2.3.x-3.x\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.0\upload_v2.1.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.1\upload_v2.3.x-3.x\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.1\upload_v2.1.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.2\upload_v2.3.x-3.x\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\PHP7.2\upload_v2.1.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template .\PHP5.4-5.6\upload_v2.3.x-3.x\admin\view\template\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template .\PHP7.0\upload_v2.3.x-3.x\admin\view\template\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template .\PHP7.1\upload_v2.3.x-3.x\admin\view\template\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template .\PHP7.2\upload_v2.3.x-3.x\admin\view\template\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template\extension\module .\PHP5.4-5.6\upload_v2.1.x-2.2\admin\view\template\module\ attributico.tpl /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template\extension\module .\PHP7.0\upload_v2.1.x-2.2\admin\view\template\module\ attributico.tpl /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template\extension\module .\PHP7.1\upload_v2.1.x-2.2\admin\view\template\module\ attributico.tpl /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template\extension\module .\PHP7.2\upload_v2.1.x-2.2\admin\view\template\module\ attributico.tpl /S