ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\system\library\attributico .\upload_no_encoded_v2.1.x-2.2\system\library\attributico\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\javascript .\upload_no_encoded_v2.1.x-2.2\admin\view\javascript\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\stylesheet .\upload_no_encoded_v2.1.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\view\template\extension\module .\upload_no_encoded_v2.1.x-2.2\admin\view\template\module\ attributico.tpl /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\model .\upload_no_encoded_v2.1.x-2.2\admin\model\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language .\upload_no_encoded_v2.1.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\en-gb\extension .\upload_no_encoded_v2.1.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\ru-ru\extension .\upload_no_encoded_v2.1.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\language\uk-ua\extension .\upload_no_encoded_v2.1.x-2.2\admin\language\ukrainian\ * /S
ROBOCOPY .\upload_no_encoded_v2.3.x-3.x\admin\controller\extension .\upload_no_encoded_v2.1.x-2.2\admin\controller\ * /S
