ROBOCOPY ..\ES6_project\dist ..\PHP5.4-5.6\upload_v2.1.x-2.2\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP5.4-5.6\upload_v2.3.x-3.x\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.0\upload_v2.1.x-2.2\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.0\upload_v2.3.x-3.x\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.1\upload_v2.1.x-2.2\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.1\upload_v2.3.x-3.x\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.2\upload_v2.1.x-2.2\admin\view\javascript\ * /S
ROBOCOPY ..\ES6_project\dist ..\PHP7.2\upload_v2.3.x-3.x\admin\view\javascript\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP5.4-5.6\upload_v2.1.x-2.2\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP5.4-5.6\upload_v2.3.x-3.x\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.0\upload_v2.1.x-2.2\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.0\upload_v2.3.x-3.x\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.1\upload_v2.1.x-2.2\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.1\upload_v2.3.x-3.x\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.2\upload_v2.1.x-2.2\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\fancytree ..\PHP7.2\upload_v2.3.x-3.x\admin\view\javascript\fancytree\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP5.4-5.6\upload_v2.1.x-2.2\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP5.4-5.6\upload_v2.3.x-3.x\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.0\upload_v2.1.x-2.2\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.0\upload_v2.3.x-3.x\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.1\upload_v2.1.x-2.2\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.1\upload_v2.3.x-3.x\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.2\upload_v2.1.x-2.2\admin\view\javascript\jquery\ * /S
ROBOCOPY ..\upload_no_encoded_v2.3.x-3.x\admin\view\javascript\jquery ..\PHP7.2\upload_v2.3.x-3.x\admin\view\javascript\jquery\ * /S